'use client';
import { useEffect, useMemo, useState } from 'react';
import { AdminShell, useAdminSession } from '../../../components/AdminShell';
import { request } from '../../../lib/api';

type Transaction = { id: string; provider: string; provider_reference: string | null; amount: number; status: string; booking_number: string; ground_title: string; player_name: string; vendor_name: string; created_at: string; paid_at: string | null };
export default function TransactionsPage() {
  const ready = useAdminSession(); const [items, setItems] = useState<Transaction[]>([]); const [status, setStatus] = useState('all'); const [query, setQuery] = useState(''); const [message, setMessage] = useState('');
  async function load() { if (!ready) return; try { const data = await request(`/transactions?status=${status}`) as { transactions: Transaction[] }; setItems(data.transactions); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load transactions.'); } }
  useEffect(() => { void load(); }, [ready, status]); const visible = useMemo(() => items.filter((item) => `${item.booking_number} ${item.ground_title} ${item.player_name} ${item.vendor_name}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  return <AdminShell active="transactions"><header><div><p className="eyebrow">FINANCIAL RECORDS</p><h1>Transactions <small>({items.length} total)</small></h1></div></header>{message && <p className="banner-error">{message}</p>}<p className="muted compact">Read-only payment-attempt records. Refunds and payouts will be enabled when the payment gateway is integrated.</p><div className="toolbar"><input placeholder="Search booking, ground, player…" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All payment statuses</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></div><section className="data-table"><div className="table-head transaction-table"><span>Booking</span><span>Ground</span><span>Player / vendor</span><span>Amount</span><span>Status</span><span>Date</span></div>{visible.map((item) => <div className="table-row transaction-table" key={item.id}><span><b>{item.booking_number}</b><small>{item.provider}</small></span><span>{item.ground_title}</span><span>{item.player_name} <small>→ {item.vendor_name}</small></span><span><b>Rs {item.amount.toLocaleString()}</b></span><span><em className={item.status === 'paid' ? 'badge live' : item.status === 'failed' ? 'badge suspended' : 'badge pending'}>{item.status.replace('_', ' ')}</em></span><span>{new Date(item.paid_at || item.created_at).toLocaleDateString()}</span></div>)}{visible.length === 0 && <p className="empty">No transaction records match this view.</p>}</section></AdminShell>;
}
