'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { AdminShell, useAdminSession } from '../../../../components/AdminShell';
import { request } from '../../../../lib/api';
type Detail = { vendor: { business_name: string; business_phone: string; business_city: string; business_description: string | null; verification_status: string; is_active: boolean; is_verified: boolean; rating: number; total_reviews: number; total_earnings: number; pending_earnings: number; owner: { full_name: string; phone: string | null; email: string | null; city: string | null; is_suspended: boolean } }; grounds: { id: string; title: string; city: string; address: string; pitch_type: string | null; is_active: boolean; verification_status: string; rating: number }[] };
const label = (value: string | null) => value ? value.replace(/_/g, ' ') : '—';
export default function VendorDetailPage() { const ready = useAdminSession(); const { id } = useParams<{ id: string }>(); const [detail, setDetail] = useState<Detail | null>(null); const [message, setMessage] = useState(''); async function load() { if (!ready || !id) return; try { setDetail(await request(`/vendors/${id}`) as Detail); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load vendor.'); } } useEffect(() => { void load(); }, [ready, id]); const vendor = detail?.vendor; return <AdminShell active="vendors"><header className="review-page-header"><div><Link className="back-link" href="/dashboard/vendors">← Back to vendors</Link><p className="eyebrow">VENDOR PROFILE</p><h1>{vendor?.business_name || 'Loading vendor…'}</h1><p className="muted compact">{vendor?.business_city || ''}</p></div><button className="refresh" onClick={() => void load()}>Refresh</button></header>{message ? <p className="banner-error">{message}</p> : null}{vendor ? <main className="review-workspace"><section className="review-card"><div className="review-card-head"><div><p className="eyebrow">ACCOUNT</p><h2>Business and owner</h2></div><em className={`review-status ${vendor.is_verified ? 'approved' : ''}`}>{label(vendor.verification_status)}</em></div><dl className="review-facts"><div><dt>Business phone</dt><dd>{vendor.business_phone}</dd></div><div><dt>Owner</dt><dd>{vendor.owner.full_name || '—'}</dd></div><div><dt>Owner phone</dt><dd>{vendor.owner.phone || '—'}</dd></div><div><dt>Email</dt><dd>{vendor.owner.email || '—'}</dd></div><div><dt>Rating</dt><dd>{vendor.rating.toFixed(1)} · {vendor.total_reviews} reviews</dd></div><div><dt>Account status</dt><dd>{vendor.is_active ? 'Active' : 'Inactive'}{vendor.owner.is_suspended ? ' · Owner suspended' : ''}</dd></div></dl><p className="muted compact">{vendor.business_description || 'No business description provided.'}</p></section><section className="review-card"><div className="review-card-head"><div><p className="eyebrow">MANAGED GROUNDS</p><h2>{detail.grounds.length} grounds</h2></div></div><div className="managed-grounds">{detail.grounds.map((ground) => <article key={ground.id}><div><b>{ground.title}</b><p>{ground.city} · {ground.address}</p><small>{ground.pitch_type || 'Pitch type not set'} · Rating {ground.rating.toFixed(1)}</small></div><em className={`badge ${ground.is_active ? 'live' : 'suspended'}`}>{label(ground.verification_status)}</em></article>)}{!detail.grounds.length ? <p className="muted compact">This vendor has not added any grounds yet.</p> : null}</div></section></main> : null}</AdminShell>; }
