'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { AdminShell, useAdminSession } from '../../../../components/AdminShell';
import { request } from '../../../../lib/api';

type Document = { id: string; type: string; originalFilename: string | null };
type Detail = { vendor: { id: string; business_name: string; business_city: string }; verification: null | { status: string; identity_status: string; business_status: string; payout_status: string; identity_reason: string | null; business_reason: string | null; payout_reason: string | null; cnic_last_four: string | null; business_type: string | null; business_number_last_four: string | null; registrant_relationship: string; payout_bank_name: string | null; payout_account_title: string | null; documents: Document[] } };
const label = (value: string | null | undefined) => value ? value.replace(/_/g, ' ') : 'Not provided';

export default function VendorVerificationReviewPage() {
  const ready = useAdminSession(); const params = useParams<{ id: string }>();
  const [detail, setDetail] = useState<Detail | null>(null); const [message, setMessage] = useState(''); const [working, setWorking] = useState(false);
  async function load() { if (!ready || !params.id) return; try { setMessage(''); setDetail(await request(`/vendors/${params.id}/verification`) as Detail); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load this application.'); } }
  useEffect(() => { void load(); }, [ready, params.id]);
  async function review(area: 'identity' | 'business' | 'payout', action: 'approved' | 'rejected' | 'changes_requested') { if (!detail?.verification) return; const reason = action === 'approved' ? null : window.prompt(action === 'rejected' ? 'Reason for rejection:' : 'Describe the required changes:'); if (action !== 'approved' && !reason) return; try { setWorking(true); await request(`/vendors/${detail.vendor.id}/verification/${area}`, { method: 'PATCH', body: JSON.stringify({ action, reason }) }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save this decision.'); } finally { setWorking(false); } }
  async function openDocument(id: string) { try { const result = await request(`/verification-documents/${id}/download`) as { download_url: string }; window.open(result.download_url, '_blank', 'noopener,noreferrer'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Document could not be opened.'); } }
  async function approveVendor() { if (!detail) return; try { setWorking(true); await request(`/vendors/${detail.vendor.id}/approve`, { method: 'POST', body: '{}' }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to approve this vendor.'); } finally { setWorking(false); } }
  const card = (title: string, area: 'identity' | 'business' | 'payout', status: string, reason: string | null, body: React.ReactNode) => <section className="review-card"><div className="review-card-head"><div><p className="eyebrow">{area}</p><h2>{title}</h2></div><em className={`review-status ${status}`}>{label(status)}</em></div>{body}{reason ? <p className="review-reason"><b>Previous review note:</b> {reason}</p> : null}<div className="review-actions"><button disabled={working} className="approve" onClick={() => void review(area, 'approved')}>Approve</button><button disabled={working} className="outline" onClick={() => void review(area, 'changes_requested')}>Request changes</button><button disabled={working} className="danger" onClick={() => void review(area, 'rejected')}>Reject</button></div></section>;
  const verification = detail?.verification;
  const allChecksApproved = Boolean(verification && [verification.identity_status, verification.business_status, verification.payout_status].every((status) => status === 'approved'));
  return <AdminShell active="vendor_verification"><header className="review-page-header"><div><Link className="back-link" href="/dashboard/vendor-verification">← Back to queue</Link><p className="eyebrow">VENDOR APPLICATION</p><h1>{detail?.vendor.business_name || 'Loading application…'}</h1><p className="muted compact">{detail?.vendor.business_city || 'Loading location…'}</p></div><button className="refresh" disabled={working} onClick={() => void load()}>Refresh</button></header>{message ? <p className="banner-error">{message}</p> : null}{!verification && !message ? <p className="empty">Loading verification details…</p> : null}{verification ? <main className="review-workspace"><section className="review-overview"><span>Application status</span><strong>{label(verification.status)}</strong><p>Approve all three sections to allow vendor mode and ground creation.</p></section>{allChecksApproved ? <section className="final-approval"><div><p className="eyebrow">FINAL DECISION</p><h2>All checks approved</h2><p>Approve this vendor account to unlock vendor mode and ground creation.</p></div><button disabled={working || verification.status === 'approved'} className="approve" onClick={() => void approveVendor()}>{verification.status === 'approved' ? 'Vendor approved' : 'Approve vendor'}</button></section> : null}{card('Identity verification', 'identity', verification.identity_status, verification.identity_reason, <><dl className="review-facts"><div><dt>CNIC</dt><dd>Ending {verification.cnic_last_four || 'not submitted'}</dd></div><div><dt>Documents</dt><dd>{verification.documents.filter((document) => document.type.startsWith('cnic_')).length} uploaded</dd></div></dl><Documents documents={verification.documents.filter((document) => document.type.startsWith('cnic_'))} onOpen={openDocument} /></>)}{card('Business verification', 'business', verification.business_status, verification.business_reason, <><dl className="review-facts"><div><dt>Business type</dt><dd>{label(verification.business_type)}</dd></div><div><dt>Registration number</dt><dd>Ending {verification.business_number_last_four || 'not submitted'}</dd></div><div><dt>Relationship</dt><dd>{label(verification.registrant_relationship)}</dd></div></dl><Documents documents={verification.documents.filter((document) => ['business_registration', 'authorization_letter'].includes(document.type))} onOpen={openDocument} /></>)}{card('Payout details', 'payout', verification.payout_status, verification.payout_reason, <dl className="review-facts"><div><dt>Bank</dt><dd>{verification.payout_bank_name || 'Not provided'}</dd></div><div><dt>Account title</dt><dd>{verification.payout_account_title || 'Not provided'}</dd></div><div><dt>Account number</dt><dd>Encrypted — never displayed</dd></div></dl>)}</main> : null}</AdminShell>;
}

function Documents({ documents, onOpen }: { documents: Document[]; onOpen: (id: string) => Promise<void> }) { return <div className="review-documents">{documents.length ? documents.map((document) => <button className="document-button" key={document.id} onClick={() => void onOpen(document.id)}><span>View {label(document.type)}</span><small>{document.originalFilename || 'Private document'}</small></button>) : <p className="muted compact">No documents were submitted for this section.</p>}</div>; }
