export interface BookingProfile {
  id: string;
  booking_number: string;
  player_id: string;
  vendor_id: string;
  ground_id: string;
  slot_id: string;
  ground_title: string;
  ground_address: string;
  player_name: string;
  player_phone: string | null;
  date: string;
  start_time: string;
  end_time: string;
  total_amount: number;
  platform_fee: number;
  vendor_amount: number;
  status: 'pending_payment' | 'confirmed' | 'cancelled' | 'expired' | 'completed' | 'no_show';
  payment_status: 'pending' | 'paid' | 'failed' | 'cancelled' | 'refund_pending' | 'refunded';
  payment_method: string;
  payment_reference: string | null;
  hold_expires_at: string | null;
  cancelled_at: string | null;
  cancellation_reason: string | null;
  cancellation_fee: number;
  refund_amount: number;
  notes: string | null;
  created_at: string;
  updated_at: string;
}
