'use client';
import { useEffect, useState } from 'react';
import { AdminShell, useAdminSession } from '../../../components/AdminShell';
import { request } from '../../../lib/api';
type Vendor = { id: string; business_name: string; business_city: string; verification_status: string; owner: { full_name: string; phone: string | null } };
type Detail = { vendor: { id: string; business_name: string; business_city: string }; verification: null | { status: string; identity_status: string; identity_reason: string | null; business_status: string; business_reason: string | null; payout_status: string; payout_reason: string | null; cnic_last_four: string | null; business_type: string | null; business_number_last_four: string | null; registrant_relationship: string; payout_bank_name: string | null; payout_account_title: string | null; documents: { id: string; type: string; contentType: string; originalFilename: string | null }[] } };
export default function VendorVerificationPage() { const ready = useAdminSession(); const [vendors, setVendors] = useState<Vendor[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [message, setMessage] = useState('');
  async function load() { if (!ready) return; try { setVendors((await request('/vendors?status=under_review') as { vendors: Vendor[] }).vendors); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load vendor queue.'); } }
  useEffect(() => { void load(); }, [ready]); async function open(id: string) { try { setDetail(await request(`/vendors/${id}/verification`) as Detail); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load verification.'); } }
  async function review(area: 'identity' | 'business' | 'payout', action: 'approved' | 'rejected' | 'changes_requested') { if (!detail?.verification) return; const reason = action === 'approved' ? null : window.prompt(action === 'rejected' ? 'Reason for rejection:' : 'Describe the required changes:'); if (action !== 'approved' && !reason) return; await request(`/vendors/${detail.vendor.id}/verification/${area}`, { method: 'PATCH', body: JSON.stringify({ action, reason }) }); await open(detail.vendor.id); await load(); }
  async function document(id: string) { try { const data = await request(`/verification-documents/${id}/download`) as { download_url: string }; window.open(data.download_url, '_blank', 'noopener,noreferrer'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Document could not be opened.'); } }
  const area = (title: string, key: 'identity' | 'business' | 'payout', status: string, children: React.ReactNode) => <section className="queue"><div className="queue-title"><h2>{title}</h2><span>{status.replace('_', ' ')}</span></div><div className="review-body">{children}<div className="actions"><button className="approve" onClick={() => void review(key, 'approved')}>Approve</button><button className="outline" onClick={() => void review(key, 'changes_requested')}>Request changes</button><button className="danger" onClick={() => void review(key, 'rejected')}>Reject</button></div></div></section>;
  return <AdminShell active="vendor_verification"><header><div><p className="eyebrow">VENDOR COMPLIANCE</p><h1>Vendor verification</h1></div></header>{message && <p className="banner-error">{message}</p>}<section className="data-table"><div className="table-head"><span>Business</span><span>Owner</span><span>City</span><span>Status</span><span /></div>{vendors.map((vendor) => <button className="table-row" key={vendor.id} onClick={() => void open(vendor.id)}><b>{vendor.business_name}</b><span>{vendor.owner.full_name}</span><span>{vendor.business_city}</span><span><em className="badge pending">{vendor.verification_status.replace('_', ' ')}</em></span><span>Review</span></button>)}{vendors.length === 0 && <p className="empty">No vendor applications are waiting for review.</p>}</section>{detail?.verification && <aside className="detail-drawer wide"><button className="close" onClick={() => setDetail(null)}>×</button><p className="eyebrow">{detail.vendor.business_name}</p><h2>Verification review</h2>{area('Identity', 'identity', detail.verification.identity_status, <><p className="muted">CNIC ending {detail.verification.cnic_last_four || '—'}</p><Documents documents={detail.verification.documents.filter((doc) => doc.type.startsWith('cnic_'))} onOpen={document} /></>)}{area('Business', 'business', detail.verification.business_status, <><p className="muted">{detail.verification.business_type?.replace('_', ' ') || '—'} · Registration ending {detail.verification.business_number_last_four || '—'} · {detail.verification.registrant_relationship.replace('_', ' ')}</p><Documents documents={detail.verification.documents.filter((doc) => ['business_registration','authorization_letter'].includes(doc.type))} onOpen={document} /></>)}{area('Payout details', 'payout', detail.verification.payout_status, <p className="muted">{detail.verification.payout_bank_name || '—'} · {detail.verification.payout_account_title || '—'}<br />Account number remains encrypted and is not displayed.</p>)}</aside>}</AdminShell>; }
function Documents({ documents, onOpen }: { documents: { id: string; type: string; originalFilename: string | null }[]; onOpen: (id: string) => Promise<void> }) { return <div className="document-list">{documents.map((doc) => <button className="outline" key={doc.id} onClick={() => void onOpen(doc.id)}>View {doc.type.replace('_', ' ')}{doc.originalFilename ? ` (${doc.originalFilename})` : ''}</button>)}</div>; }
