import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useRef, useState } from 'react';
import { Animated, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { markOnboardingSeen } from '@/lib/onboarding';

const slides=[
  {tag:'KARACHI & LAHORE',icon:'location' as const,title:'GROUNDS NEAR YOU, LIVE',body:'See real-time availability at verified grounds in your city — no more calling around.',art:'pitch'},
  {tag:'BOOK IN SECONDS',icon:'calendar' as const,title:'PICK. BOOK. PLAY.',body:'Choose a ground, select a slot, and keep your game plan simple.',art:'slots'},
  {tag:'RALLY MODE',icon:'people' as const,title:'RALLY YOUR SQUAD',body:'Create teams, invite friends, and split costs — all inside the app.',art:'squad'},
];
export default function Onboarding(){const [index,setIndex]=useState(0);const fade=useRef(new Animated.Value(1)).current;const slide=slides[index];const change=async(next:number)=>{if(next===3){await markOnboardingSeen();router.replace('/(auth)/phone-input');return;} Animated.sequence([Animated.timing(fade,{toValue:0,duration:160,useNativeDriver:true}),Animated.timing(fade,{toValue:1,duration:250,useNativeDriver:true})]).start();setIndex(next)};return <SafeAreaView style={s.safe}><View style={s.top}><Text style={s.brand}><Text style={{color:'#3EAF4C'}}>TURF</Text>BOOKPK</Text><Pressable accessibilityRole="button" accessibilityLabel="Skip onboarding" onPress={()=>change(3)}><Text style={s.skip}>Skip</Text></Pressable></View><Animated.View style={[s.main,{opacity:fade}]}><View style={s.art}><View style={s.glow}/><View style={s.mock}><View style={s.badge}><Ionicons name={slide.icon} size={14} color="#3EAF4C"/><Text style={s.badgeText}>{slide.tag}</Text></View>{slide.art==='slots'?<><Text style={s.mockTitle}>Total Football Arena</Text><View style={s.slot}><Text style={s.slotText}>09:00 PM – 10:00 PM</Text><Text style={s.slotPrice}>PKR 4,500</Text></View><View style={s.slot}><Text style={s.slotText}>10:00 PM – 11:00 PM</Text><Text style={s.booked}>Booked</Text></View></>:<Ionicons name={slide.art==='squad'?'people-outline':'football-outline'} size={84} color="rgba(62,175,76,.72)"/>}</View></View><View style={s.panel}><Text style={s.heading}>{slide.title}</Text><Text style={s.body}>{slide.body}</Text><View style={s.controls}><View style={s.dots}>{slides.map((_,i)=><View key={i} style={[s.dot,i===index&&s.dotActive]}/>)}</View><Pressable accessibilityRole="button" accessibilityLabel={index===2?'Get started':'Next onboarding screen'} onPress={()=>change(index+1)} style={s.next}><Text style={s.nextText}>{index===2?'Get started':'Next'}</Text><Ionicons name="arrow-forward" size={16} color="white"/></Pressable></View></View></Animated.View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#12130F'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:24,paddingTop:12},brand:{color:'#F5F5F0',fontSize:20,fontFamily:'BigShouldersDisplay_800ExtraBold'},skip:{color:'#A1A39D',fontFamily:'SpaceGrotesk_700Bold',fontSize:14},main:{flex:1,justifyContent:'space-between'},art:{height:350,justifyContent:'center',alignItems:'center',overflow:'hidden'},glow:{position:'absolute',width:280,height:280,borderRadius:140,backgroundColor:'rgba(62,175,76,.11)',top:20,left:-80},mock:{width:310,height:280,borderRadius:22,borderWidth:1,borderColor:'rgba(62,175,76,.25)',backgroundColor:'#1A1C16',alignItems:'center',justifyContent:'center',padding:18},badge:{position:'absolute',top:14,left:14,flexDirection:'row',gap:6,alignItems:'center',backgroundColor:'#2A2C25',paddingHorizontal:10,paddingVertical:7,borderRadius:99},badgeText:{color:'#F5F5F0',fontFamily:'SpaceGrotesk_700Bold',fontSize:10},mockTitle:{color:'#F5F5F0',fontFamily:'SpaceGrotesk_700Bold',fontSize:16,alignSelf:'flex-start',marginTop:32,marginBottom:16},slot:{width:'100%',flexDirection:'row',justifyContent:'space-between',padding:11,backgroundColor:'#24271F',borderRadius:10,marginBottom:8},slotText:{color:'#F5F5F0',fontFamily:'SpaceGrotesk_500Medium',fontSize:11},slotPrice:{color:'#3EAF4C',fontFamily:'SpaceGrotesk_700Bold',fontSize:11},booked:{color:'#A1A39D',fontFamily:'SpaceGrotesk_700Bold',fontSize:11},panel:{backgroundColor:'#1A1C16',borderTopWidth:1,borderColor:'#282C23',borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:24},heading:{color:'#F5F5F0',fontFamily:'BigShouldersDisplay_800ExtraBold',fontSize:28,lineHeight:30},body:{color:'#A1A39D',fontFamily:'SpaceGrotesk_400Regular',fontSize:14,lineHeight:21,marginTop:10},controls:{marginTop:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},dots:{flexDirection:'row',gap:8},dot:{height:7,width:7,borderRadius:4,backgroundColor:'rgba(161,163,157,.4)'},dotActive:{width:21,backgroundColor:'#3EAF4C'},next:{flexDirection:'row',gap:7,alignItems:'center',backgroundColor:'#3EAF4C',paddingHorizontal:22,paddingVertical:12,borderRadius:99},nextText:{color:'white',fontFamily:'SpaceGrotesk_700Bold',fontSize:14}});
