'use client';

import { useEffect, useMemo, useState } from 'react';
import { AdminShell, useAdminSession } from '../../../components/AdminShell';
import { request } from '../../../lib/api';

type Ground = { id: string; title: string; city: string; address: string; pitch_type: string | null; price_per_hour: number; verification_status: string; is_active: boolean; images: string[]; cover_image: string | null; vendor: { id: string; business_name: string }; created_at: string };
export default function GroundsPage() {
  const token = useAdminSession(); const [items, setItems] = useState<Ground[]>([]); const [status, setStatus] = useState('all'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Ground | null>(null); const [message, setMessage] = useState('');
  async function load() { if (!token) return; try { const result = await request(`/grounds?status=${status}`) as { grounds: Ground[] }; setItems(result.grounds); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load grounds.'); } }
  useEffect(() => { void load(); }, [token, status]);
  const filtered = useMemo(() => items.filter((item) => `${item.title} ${item.city} ${item.vendor.business_name}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  async function verify(id: string, next: 'approved' | 'rejected') { const reason = next === 'rejected' ? window.prompt('Reason for rejection:') : null; if (next === 'rejected' && !reason) return; await request(`/grounds/${id}/verification`, { method: 'PATCH', body: JSON.stringify({ status: next, reason }) }); setSelected(null); void load(); }
  async function toggle(item: Ground) { const reason = item.is_active ? window.prompt('Reason for suspending this listing:') : null; if (item.is_active && !reason) return; await request(`/grounds/${item.id}/activation`, { method: 'PATCH', body: JSON.stringify({ is_active: !item.is_active, reason }) }); setSelected(null); void load(); }
  return <AdminShell active="grounds"><header><div><p className="eyebrow">MARKETPLACE OPERATIONS</p><h1>Ground Listings <small>({items.length} total)</small></h1></div></header>{message && <p className="banner-error">{message}</p>}<div className="toolbar"><input placeholder="Search by ground or owner…" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending review</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div><section className="data-table"><div className="table-head"><span>Ground</span><span>Owner</span><span>City</span><span>Status</span><span /></div>{filtered.map((item) => <button className="table-row" key={item.id} onClick={() => setSelected(item)}><span className="listing-name"><i>{item.cover_image || item.images[0] ? <img src={item.cover_image || item.images[0]} alt="" /> : '⚽'}</i><b>{item.title}</b></span><span>{item.vendor.business_name}</span><span>{item.city}</span><span><em className={item.is_active ? item.verification_status === 'approved' ? 'badge live' : 'badge pending' : 'badge suspended'}>{item.is_active ? item.verification_status : 'suspended'}</em></span><span>›</span></button>)}{filtered.length === 0 && <p className="empty">No grounds match this view.</p>}</section>{selected && <aside className="detail-drawer"><button className="close" onClick={() => setSelected(null)}>×</button><p className="eyebrow">LISTING DETAILS</p>{selected.cover_image && <img className="ground-cover" src={selected.cover_image} alt="" />}<h2>{selected.title}</h2><p className="muted">{selected.address}, {selected.city}</p><dl><div><dt>Pitch type</dt><dd>{selected.pitch_type || 'Not specified'}</dd></div><div><dt>Price</dt><dd>Rs {selected.price_per_hour}/hr</dd></div><div><dt>Owner</dt><dd>{selected.vendor.business_name}</dd></div></dl><div className="drawer-actions">{selected.verification_status !== 'approved' && <button className="approve" onClick={() => void verify(selected.id, 'approved')}>Approve listing</button>}{selected.verification_status !== 'rejected' && <button className="outline" onClick={() => void verify(selected.id, 'rejected')}>Reject listing</button>}<button className={selected.is_active ? 'danger' : 'approve'} onClick={() => void toggle(selected)}>{selected.is_active ? 'Suspend listing' : 'Restore listing'}</button></div></aside>}</AdminShell>;
}
