import { Linking, ScrollView, StatusBar, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { goBackOrReplace } from '@/lib/navigation';
import { appDialog } from '@/components/ui/app-dialog';

export default function HelpSupportScreen() {
  const openSupport = () => Linking.openURL('mailto:support@turfbookpk.com?subject=TurfBookPK%20support').catch(() => appDialog.alert('Contact support', 'Email support@turfbookpk.com for help.'));
  const row = (title: string, text: string) => <View className="bg-[#20241D] rounded-[18px] p-4 mb-3"><Text className="text-[#F3F4EF] font-semibold text-base">{title}</Text><Text className="text-[#AFAFA9] text-sm leading-5 mt-2">{text}</Text></View>;
  return <SafeAreaView edges={['top', 'left', 'right']} className="flex-1 bg-[#10120F]"><StatusBar barStyle="light-content" backgroundColor="#10120F" /><ScrollView contentContainerStyle={{ paddingBottom: 30 }}><View className="px-5 pt-3 pb-4 flex-row items-center"><TouchableOpacity accessibilityRole="button" accessibilityLabel="Go back" onPress={() => goBackOrReplace('/(player)/profile')} className="w-10 h-10 rounded-xl border border-[#30372B] items-center justify-center mr-3"><Ionicons name="arrow-back" size={23} color="#F8F7F0" /></TouchableOpacity><Text style={{ fontFamily: 'BigShouldersDisplay_800ExtraBold', fontSize: 26 }} className="text-[#F8F7F0]">HELP & SUPPORT</Text></View><View className="px-5"><View className="bg-[#19331D] border border-[#315536] rounded-[20px] p-5"><Ionicons name="help-buoy-outline" size={30} color="#3DB54A" /><Text style={{ fontFamily: 'SpaceGrotesk_700Bold' }} className="text-[#F8F7F0] text-lg mt-3">How can we help?</Text><Text className="text-[#BFC1B9] text-sm leading-5 mt-1">Get help with bookings, payments, cancellations, or your account.</Text><TouchableOpacity accessibilityRole="button" onPress={openSupport} className="bg-[#3DB54A] rounded-full py-3 items-center mt-5"><Text className="text-white font-semibold">Contact support</Text></TouchableOpacity></View><Text style={{ fontFamily: 'BigShouldersDisplay_700Bold', fontSize: 18 }} className="text-[#91958D] mt-7 mb-3">COMMON QUESTIONS</Text>{row('How do I cancel a booking?', 'Open the booking from My Bookings and choose Cancel booking. The refund shown follows the venue cancellation policy.')}{row('Where is my payment history?', 'Open Wallet & Payments in Profile to see payments from your booking history.')}{row('Why is a slot unavailable?', 'Slots can be booked, blocked by the venue, or temporarily held while another player completes checkout.')}</View></ScrollView></SafeAreaView>;
}
