import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Image, ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import * as Location from 'expo-location';
import { Ground, searchPublicGrounds } from '@/lib/api/vendors';

type Nearby = { ground: Ground; distance: number | null; slots: number };
const today = () => new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString().slice(0, 10);
const distance = (from: { latitude: number; longitude: number }, ground: Ground) => { if (ground.latitude === null || ground.longitude === null) return null; const r = (v: number) => v * Math.PI / 180; const a = Math.sin(r(ground.latitude - from.latitude) / 2) ** 2 + Math.cos(r(from.latitude)) * Math.cos(r(ground.latitude)) * Math.sin(r(ground.longitude - from.longitude) / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); };

export default function NearbyGroundsScreen() {
  const [grounds, setGrounds] = useState<Nearby[]>([]); const [loading, setLoading] = useState(true); const [locationDenied, setLocationDenied] = useState(false);
  const load = useCallback(async () => { try { const permission = await Location.requestForegroundPermissionsAsync(); setLocationDenied(!permission.granted); const position = permission.granted ? await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }) : null; const result = await searchPublicGrounds({ availability_date: today(), page: 1, limit: 50, sort: 'recommended' }); const data = result.grounds.map((ground) => ({ ground, slots: (result.slots_by_ground[ground.id] || []).filter((slot) => slot.date === today() && !slot.is_booked && !slot.is_blocked && !slot.is_held).length, distance: position ? distance({ latitude: position.coords.latitude, longitude: position.coords.longitude }, ground) : null })).filter((item) => item.slots > 0); data.sort((a, b) => a.distance === null ? 1 : b.distance === null ? -1 : a.distance - b.distance); setGrounds(data); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  return <SafeAreaView edges={['top', 'left', 'right']} className="flex-1 bg-[#10120F]"><View className="px-5 pt-4 pb-3 flex-row items-center"><TouchableOpacity onPress={() => router.back()} className="w-10 h-10 border border-[#30372B] rounded-xl items-center justify-center mr-3"><Ionicons name="arrow-back" size={22} color="#F8F7F0" /></TouchableOpacity><View><Text style={{ fontFamily: 'BigShouldersDisplay_800ExtraBold', fontSize: 26 }} className="text-[#F8F7F0]">NEAR YOU</Text><Text className="text-[#AFAFA9] text-[11px]">Closest grounds with slots today</Text></View></View>{loading ? <View className="flex-1 items-center justify-center"><ActivityIndicator color="#3DB54A" /></View> : <ScrollView contentContainerStyle={{ padding: 20, paddingTop: 8 }}>{locationDenied && <Text className="text-[#E5B85B] text-xs mb-3">Allow location to sort these grounds by distance.</Text>}{grounds.map(({ ground, distance: km, slots }) => <TouchableOpacity key={ground.id} onPress={() => router.push({ pathname: '/(player)/ground/[id]', params: { id: ground.id } })} className="bg-[#20241D] border border-[#30372B] rounded-2xl mb-3 overflow-hidden flex-row"><Image source={{ uri: ground.cover_image || ground.images[0] || 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800' }} className="w-28 h-28" /><View className="flex-1 p-3 justify-between"><View><Text style={{ fontFamily: 'SpaceGrotesk_700Bold' }} className="text-[#F3F4EF] text-base" numberOfLines={1}>{ground.title}</Text><Text className="text-[#AFAFA9] text-xs mt-1" numberOfLines={1}>{ground.location}</Text></View><Text className="text-[#59C462] text-xs">{km === null ? `${slots} slots today` : `${km.toFixed(1)} km away · ${slots} today`}</Text></View></TouchableOpacity>)}{!grounds.length && <Text className="text-[#AFAFA9] text-sm text-center py-16">No nearby grounds have slots today.</Text>}</ScrollView>}</SafeAreaView>;
}
