import { useState } from 'react';
import { ScrollView, StatusBar, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { createReview } from '@/lib/api/reviews';
import { Toast } from '@/components/ui/toast';
import { goBackOrReplace } from '@/lib/navigation';

export default function WriteReview() {
  const { bookingId, title } = useLocalSearchParams<{ bookingId: string; title?: string }>(); const [rating, setRating] = useState(0); const [comment, setComment] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const save = async () => { if (!bookingId || rating < 1) return setError('Choose a rating from 1 to 5 stars.'); setSaving(true); try { await createReview(bookingId, rating, comment); goBackOrReplace('/(player)/bookings'); } catch (caught: any) { setError(caught?.message || 'Unable to submit review.'); } finally { setSaving(false); } };
  return <SafeAreaView edges={['top', 'left', 'right']} className="flex-1 bg-[#10120F]"><StatusBar barStyle="light-content" backgroundColor="#10120F" /><ScrollView className="px-5" contentContainerStyle={{ paddingBottom: 40 }}><View className="flex-row items-center py-4"><TouchableOpacity accessibilityRole="button" accessibilityLabel="Go back" onPress={() => goBackOrReplace('/(player)/bookings')} className="h-10 w-10 rounded-xl border border-[#30372B] items-center justify-center"><Ionicons name="arrow-back" size={22} color="#F8F7F0" /></TouchableOpacity><Text style={{ fontFamily: 'BigShouldersDisplay_800ExtraBold', fontSize: 25 }} className="text-[#F8F7F0] ml-3">RATE YOUR EXPERIENCE</Text></View><Text className="text-[#BFC1B9] text-[16px] mt-3">How was your game at <Text className="text-[#3DB54A]">{title || 'this ground'}</Text>?</Text><View className="bg-[#20241D] border border-[#30372B] rounded-[20px] p-5 mt-6"><Text style={{ fontFamily: 'BigShouldersDisplay_700Bold', fontSize: 18 }} className="text-[#BFC1B9]">YOUR RATING</Text><View className="flex-row mt-4 justify-between">{[1, 2, 3, 4, 5].map((value) => <TouchableOpacity key={value} accessibilityRole="button" accessibilityLabel={`${value} stars`} accessibilityState={{ selected: value === rating }} onPress={() => setRating(value)}><Ionicons name={value <= rating ? 'star' : 'star-outline'} size={38} color="#F5A623" /></TouchableOpacity>)}</View></View><Text style={{ fontFamily: 'BigShouldersDisplay_700Bold', fontSize: 18 }} className="text-[#BFC1B9] mt-7 mb-2">COMMENT (OPTIONAL)</Text><TextInput value={comment} onChangeText={setComment} multiline maxLength={500} placeholder="Share your experience at this ground..." placeholderTextColor="#858A81" className="min-h-[145px] bg-[#20241D] border border-[#30372B] rounded-[20px] p-4 text-[#F8F7F0] text-[15px]" textAlignVertical="top" /><Text className="text-[#858A81] text-xs text-right mt-1">{comment.length}/500</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Submit review" disabled={saving} onPress={save} className={`rounded-full py-4 items-center mt-6 ${saving ? 'bg-[#596057]' : 'bg-[#3DB54A]'}`}><Text className="text-white font-semibold text-base">{saving ? 'Submitting...' : 'Submit review'}</Text></TouchableOpacity></ScrollView><Toast message={error} tone="error" onHide={() => setError(null)} /></SafeAreaView>;
}
