import { useState } from 'react';
import { ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { createReview } from '@/lib/api/reviews';
import { Toast } from '@/components/ui/toast';

export default function WriteReview() {
  const { bookingId, title } = useLocalSearchParams<{ bookingId: string; title?: string }>(); const [rating, setRating] = useState(0); const [comment, setComment] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const save = async () => { if (!bookingId || rating < 1) return setError('Choose a rating from 1 to 5 stars.'); setSaving(true); try { await createReview(bookingId, rating, comment); router.back(); } catch (caught: any) { setError(caught?.message || 'Unable to submit review.'); } finally { setSaving(false); } };
  return <SafeAreaView className="flex-1 bg-[#F8F9FA]"><ScrollView className="px-6" contentContainerStyle={{ paddingBottom: 40 }}><View className="flex-row items-center py-5"><TouchableOpacity onPress={() => router.back()} className="h-11 w-11 rounded-full bg-white items-center justify-center"><Ionicons name="arrow-back" size={20} color="#1A1A2E" /></TouchableOpacity><Text className="text-xl font-bold text-[#1A1A2E] ml-3">Rate your booking</Text></View><Text className="text-[#737373]">{title || 'How was your experience?'}</Text><Text className="text-[#1A1A2E] font-bold mt-7 mb-3">Your rating</Text><View className="flex-row">{[1, 2, 3, 4, 5].map((value) => <TouchableOpacity key={value} accessibilityLabel={`${value} stars`} onPress={() => setRating(value)} className="mr-3"><Ionicons name={value <= rating ? 'star' : 'star-outline'} size={38} color="#F59E0B" /></TouchableOpacity>)}</View><Text className="text-[#1A1A2E] font-bold mt-7 mb-2">Comment (optional)</Text><TextInput value={comment} onChangeText={setComment} multiline maxLength={500} placeholder="Tell other players about the ground..." className="min-h-[130px] bg-white border border-[#E5E5E5] rounded-xl p-4 text-[#1A1A2E]" textAlignVertical="top" /><Text className="text-[#737373] text-xs text-right mt-1">{comment.length}/500</Text><TouchableOpacity disabled={saving} onPress={save} className={`rounded-xl py-4 items-center mt-6 ${saving ? 'bg-[#9CA3AF]' : 'bg-[#4CAF50]'}`}><Text className="text-white font-bold">{saving ? 'Submitting...' : 'Submit review'}</Text></TouchableOpacity></ScrollView><Toast message={error} tone="error" onHide={() => setError(null)} /></SafeAreaView>;
}
