import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StatusBar, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { getPlayerBookings, BookingProfile } from '@/lib/api/bookings';
import { goBackOrReplace } from '@/lib/navigation';

export default function WalletScreen() {
  const [bookings, setBookings] = useState<BookingProfile[]>([]);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setBookings((await getPlayerBookings(1, 50)).bookings); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const paid = bookings.filter((item) => item.payment_status === 'paid').reduce((sum, item) => sum + item.total_amount, 0);
  return <SafeAreaView edges={['top', 'left', 'right']} className="flex-1 bg-[#10120F]"><StatusBar barStyle="light-content" backgroundColor="#10120F" /><View className="px-5 pt-3 pb-4 flex-row items-center"><TouchableOpacity accessibilityRole="button" accessibilityLabel="Go back" onPress={() => goBackOrReplace('/(player)/profile')} className="w-10 h-10 rounded-xl border border-[#30372B] items-center justify-center mr-3"><Ionicons name="arrow-back" size={23} color="#F8F7F0" /></TouchableOpacity><Text style={{ fontFamily: 'BigShouldersDisplay_800ExtraBold', fontSize: 24 }} className="text-[#F8F7F0]">WALLET & PAYMENTS</Text></View><FlatList data={bookings} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 32, flexGrow: 1 }} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#3DB54A" />} ListHeaderComponent={<View className="bg-[#19331D] border border-[#315536] rounded-[20px] p-5 mb-6"><Text className="text-[#BFC1B9] text-sm">Total paid through TurfBookPK</Text><Text style={{ fontFamily: 'SpaceGrotesk_700Bold' }} className="text-[#3DB54A] text-[22px] mt-1">PKR {paid.toLocaleString()}</Text><Text className="text-[#AFAFA9] text-xs mt-2">Payment history is based on confirmed bookings.</Text><Text style={{ fontFamily: 'BigShouldersDisplay_700Bold', fontSize: 16 }} className="text-[#91958D] mt-7">RECENT PAYMENTS</Text></View>} ListEmptyComponent={loading ? <ActivityIndicator color="#3DB54A" /> : <View className="items-center pt-16"><Ionicons name="card-outline" size={38} color="#3DB54A" /><Text className="text-[#F8F7F0] font-bold mt-3">No payments yet</Text><Text className="text-[#AFAFA9] text-sm mt-1">Your paid booking history will appear here.</Text></View>} renderItem={({ item }) => <View className="bg-[#20241D] rounded-[18px] px-4 py-4 mb-3 flex-row items-center"><View className={`w-10 h-10 rounded-full items-center justify-center ${item.payment_status === 'paid' ? 'bg-[#19331D]' : 'bg-[#342B18]'}`}><Ionicons name={item.payment_status === 'paid' ? 'checkmark-circle-outline' : 'time-outline'} size={21} color={item.payment_status === 'paid' ? '#3DB54A' : '#F5A623'} /></View><View className="flex-1 ml-3"><Text className="text-[#F3F4EF] font-semibold" numberOfLines={1}>{item.ground_title}</Text><Text className="text-[#AFAFA9] text-xs mt-1">{item.date} • {item.payment_status.replaceAll('_', ' ')}</Text></View><Text style={{ fontFamily: 'SpaceGrotesk_700Bold' }} className="text-[#F3F4EF]">PKR {item.total_amount.toLocaleString()}</Text></View>} /></SafeAreaView>;
}
